#默认使用dev配置
#java -jar xxx.jar --spring.profiles.active=prod
spring:
  application:
    name: config-server
server:
  port: 8830
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          searchPaths: respo
          username: your username
          password: your password
      label: master

#日志地址
logging:
  file: C:\Users\awins\Projects\logs\${spring.application.name}.log
---
# 测试环境配置
spring:
  profiles: test
---
# 正式环境配置
spring:
  profiles: prod

