#默认使用dev配置
#java -jar xxx.jar --spring.profiles.active=prod
spring:
  application:
    name: eureka-client-1
  profiles:
    active: dev
#服务注册中心端口号
server:
  port: 8881
#Eureka注册中心设置
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.61.137:8801/eureka/
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
---
# 开发环境配置
spring:
  profiles: dev
#日志地址
logging:
  file: /home/winson/logs/eureka-server.log

---
# 测试环境配置
spring:
  profiles: test
#日志地址
logging:
  file: /home/webadmin/logs/eureka-server.log

---
# 正式环境配置
spring:
  profiles: prod

