#默认使用dev配置
#java -jar xxx.jar --spring.profiles.active=prod
server:
  port: 8820
spring:
  profiles:
    active: dev
  application:
    name: consumer
logging:
  file: C:\Users\awins\Projects\logs\${spring.application.name}.log
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
#熔断器
feign:
  hystrix:
    enabled: true
#zuul配置
zuul:
  routes:
    provider:
      path: /provider/**
      serviceId: provider
    provider-spare:
      path: /provider-spare/**
      serviceId: provider-spare
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8801/eureka/,http://127.0.0.1:8802/eureka/
---
# 测试环境配置
spring:
  profiles: test

---
# 正式环境配置
spring:
  profiles: prod

