#默认使用dev配置
#java -jar xxx.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev
  application:
    name: provider
logging:
  file: /home/winson/logs/${spring.application.name}.log
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
server:
  port: 8810
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.61.137:8800/eureka/,http://192.168.61.137:8801/eureka/,http://192.168.61.137:8802/eureka/
---
# 测试环境配置
spring:
  profiles: test

---
# 正式环境配置
spring:
  profiles: prod

