#默认使用dev配置
#java -jar xxx.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev0
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
  instance:
    hostname: 192.168.61.137
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
  file: /home/winson/logs/${spring.application.name}.log
---
# 开发环境配置（单服务中心）
spring:
  profiles: dev0
server:
  port: 8800
eureka:
  client:
    #服务注册中心的配置内容，指定服务注册中心的位置(与其他注册中心互相注册)
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8800/eureka/

---
# 开发环境配置（双服务中心1）
spring:
  profiles: dev1
server:
  port: 8801
eureka:
  client:
    #服务注册中心的配置内容，指定服务注册中心的位置(与其他注册中心互相注册)
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8802/eureka/
---
# 开发环境配置（双服务中心2）
spring:
  profiles: dev2
server:
  port: 8802
eureka:
    #服务注册中心的配置内容，指定服务注册中心的位置(与其他注册中心互相注册)
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8801/eureka/

---
# 测试环境配置
spring:
  profiles: test
---
# 正式环境配置
spring:
  profiles: prod

