foo: foo v1.3
logging:
  file: C:\Users\awins\Projects\logs\${spring.application.name}.log
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
#熔断器
feign:
  hystrix:
    enabled: true
#zuul配置
zuul:
  routes:
    provider:
      path: /provider/**
      serviceId: provider
    provider-spare:
      path: /provider-spare/**
      serviceId: provider-spare
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8801/eureka/,http://127.0.0.1:8802/eureka/
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
#2.0后需要开启的配置
management:
  endpoints:
    web: 
      exposure:
        include: ["health","info","bus-refresh"]